export const FETCH_CONTACTS = "FETCH_CONTACTS"
export const SET_CONTACTS_STATISTIC = "SET_CONTACTS_STATISTIC"
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";